export const ROLES = {
  CAR_OWNER: 'CAR_OWNER',
  MECH: 'MECH',
  ADMIN: 'ADMIN',
  SPARE_PARTS_SELLER: 'seller',
};

export const ROUTES = {
  SPLASH: 'Splash',
  ONBOARDING_CAROUSEL: 'OnboardingCarousel',
  ROLE_SELECTION: 'RoleSelection',
  LOGIN: 'Login',
  SIGN_UP: 'SignUp',
  FORGOT_PASSWORD: 'ForgotPassword',
  RESET_PASSWORD: 'ResetPassword',
  OTP_VERIFICATION: 'OTPVerification',

  CAR_OWNER_DASHBOARD: 'CarOwnerDashboard',
  CAR_OWNER_HISTORY: 'CarOwnerHistory',
  CAR_OWNER_MARKETPLACE: 'CarOwnerMarketplace',
  CAR_OWNER_REWARDS: 'CarOwnerRewards',
  CAR_OWNER_FUND_WALLET: 'CarOwnerFundWallet',
  CAR_OWNER_ESCROW_FUNDING: 'CarOwnerEscrowFunding',
  CAR_OWNER_CARD_PAYMENT: 'CarOwnerCardPayment',
  CAR_OWNER_JOB_PAYSTACK_CHECKOUT: 'CarOwnerJobPaystackCheckout',
  CAR_OWNER_PAYMENT_SUCCESS: 'CarOwnerPaymentSuccess',
  CAR_OWNER_VERIFY_TOP_UP: 'CarOwnerVerifyTopUp',
  CAR_OWNER_TRANSACTION_DETAILS: 'CarOwnerTransactionDetails',
  CAR_OWNER_WITHDRAW: 'CarOwnerWithdraw',
  CAR_OWNER_SETTINGS: 'CarOwnerSettings',
  CAR_OWNER_CHAT: 'CarOwnerChat',
  CAR_OWNER_PROFILE: 'CarOwnerProfile',
  CAR_OWNER_EDIT_PROFILE: 'CarOwnerEditProfile',
  CAR_OWNER_ADD_CONTACT_SUCCESS: 'CarOwnerAddContactSuccess',
  CAR_OWNER_REPORT_ISSUE: 'CarOwnerReportIssue',
  CAR_OWNER_REQUEST_DIAGNOSTICS: 'CarOwnerRequestDiagnostics',
  CAR_OWNER_TOWING_COMPANIES: 'TowingCompanies',
  CAR_OWNER_DIAGNOSTIC_EXPERTS: 'CarOwnerDiagnosticExperts',
  CAR_OWNER_MECHANIC_DISCOVERY: 'CarOwnerMechanicDiscovery',
  CAR_OWNER_WAITING_MECHANIC: 'CarOwnerWaitingMechanic',
  CAR_OWNER_LIVE_TRACKING: 'CarOwnerLiveTracking',
  CAR_OWNER_RATE_MECHANIC: 'CarOwnerRateMechanic',
  CAR_OWNER_MECHANIC_DETAILS: 'CarOwnerMechanicDetails',
  CAR_OWNER_MECHANIC_REVIEWS: 'CarOwnerMechanicReviews',
  STORE_DETAILS: 'StoreDetails',
  CAR_OWNER_PICKUP_TRACKING: 'CarOwnerPickupTracking',
  CAR_OWNER_EDIT_JOB: 'CarOwnerEditJob',
  CHANGE_PASSWORD: 'ChangePassword',
  PERSONAL_INFO: 'PersonalInfo',
  PROFILE_BANK_DETAILS: 'ProfileBankDetails',
  SUPPORT: 'Support',
  SUPPORT_CHAT_MOCK: 'SupportChatMock',
  PRIVACY_POLICY: 'PrivacyPolicy',

  MECH_DASHBOARD: 'MechDashboard',
  MECH_DASHBOARD_TABS: 'MechanicDashboardTabs',
  MECH_PROFILE_SETUP: 'MechanicProfileSetup',
  MECH_UPLOAD_PROFILE_PHOTO: 'MechanicUploadProfilePhoto',
  MECH_UPLOAD_CERTIFICATE: 'MechanicUploadCertificate',
  MECH_SERVICE_PRICING: 'MechanicServicePricing',
  MECH_SET_SERVICES: 'MechanicSetServices',
  MECH_KYC_UPLOAD: 'MechanicKycUpload',
  MECH_ADDRESS: 'MechanicAddress',
  MECH_BANK_DETAILS: 'MechanicBankDetails',
  MECH_EDIT_PROFILE: 'MechanicEditProfile',
  MECH_CHAT: 'MechanicChat', // Added new route
  MECH_LIVE_TRACKING: 'MechanicLiveTracking',
  MECH_PICKUP_TRACKING: 'MechanicPickupTracking',
  USER_PROFILE: 'UserProfile',
  USER_REVIEWS: 'UserReviews',
  ADMIN_DASHBOARD: 'AdminDashboard',

  SPARE_PARTS_DASHBOARD: 'SparePartsDashboard',
  SPARE_PARTS_TABS: 'SparePartsTabs',
  SPARE_PARTS_PROFILE_SETUP: 'SparePartsProfileSetup',
  SPARE_PARTS_UPLOAD_CAC: 'SparePartsUploadCac',
  SPARE_PARTS_UPLOAD_NIN: 'SparePartsUploadNin',
  SPARE_PARTS_ADDRESS: 'SparePartsAddress',
  SPARE_PARTS_BANK_DETAILS: 'SparePartsBankDetails',
  SPARE_PARTS_PERSONAL_INFO: 'SparePartsPersonalInfo',
  SPARE_PARTS_ADD_PRODUCT: 'SparePartsAddProduct',
  SPARE_PARTS_PICKUP_ORDER_DETAILS: 'SparePartsPickupOrderDetails',
  SPARE_PARTS_ORDERS: 'SparePartsOrders',
  SPARE_PARTS_STORE: 'SparePartsStore',
  SPARE_PARTS_WALLET: 'SparePartsWallet',
  SPARE_PARTS_PROFILE: 'SparePartsProfile',
};
