export const ROLES = {
  CAR_OWNER: 'CAR_OWNER',
  MECH: 'MECH',
  ADMIN: 'ADMIN',
};

export const ROUTES = {
  SPLASH: 'Splash',
  ROLE_SELECTION: 'RoleSelection',
  LOGIN: 'Login',
  SIGN_UP: 'SignUp',
  FORGOT_PASSWORD: 'ForgotPassword',
  RESET_PASSWORD: 'ResetPassword',
  OTP_VERIFICATION: 'OTPVerification',

  CAR_OWNER_DASHBOARD: 'CarOwnerDashboard',
  CAR_OWNER_HISTORY: 'CarOwnerHistory',
  CAR_OWNER_REWARDS: 'CarOwnerRewards',
  CAR_OWNER_FUND_WALLET: 'CarOwnerFundWallet',
  CAR_OWNER_VERIFY_TOP_UP: 'CarOwnerVerifyTopUp',
  CAR_OWNER_TRANSACTION_DETAILS: 'CarOwnerTransactionDetails',
  CAR_OWNER_WITHDRAW: 'CarOwnerWithdraw',
  CAR_OWNER_SETTINGS: 'CarOwnerSettings',
  CAR_OWNER_CHAT: 'CarOwnerChat',
  CAR_OWNER_PROFILE: 'CarOwnerProfile',
  CAR_OWNER_EDIT_PROFILE: 'CarOwnerEditProfile',
  CAR_OWNER_ADD_CONTACT_SUCCESS: 'CarOwnerAddContactSuccess',
  CAR_OWNER_REPORT_ISSUE: 'CarOwnerReportIssue',
  CAR_OWNER_REQUEST_DIAGNOSTICS: 'CarOwnerRequestDiagnostics',
  CAR_OWNER_DIAGNOSTIC_EXPERTS: 'CarOwnerDiagnosticExperts',
  CAR_OWNER_MECHANIC_DISCOVERY: 'CarOwnerMechanicDiscovery',
  CAR_OWNER_LIVE_TRACKING: 'CarOwnerLiveTracking',
  CAR_OWNER_RATE_MECHANIC: 'CarOwnerRateMechanic',
  CAR_OWNER_MECHANIC_DETAILS: 'CarOwnerMechanicDetails',
  CAR_OWNER_MECHANIC_REVIEWS: 'CarOwnerMechanicReviews',
  CAR_OWNER_JOB_DETAILS: 'CarOwnerJobDetails',
  CAR_OWNER_EDIT_JOB: 'CarOwnerEditJob',
  CHANGE_PASSWORD: 'ChangePassword',
  SUPPORT: 'Support',

  MECH_DASHBOARD: 'MechDashboard',
  MECH_DASHBOARD_TABS: 'MechanicDashboardTabs',
  MECH_PROFILE_SETUP: 'MechanicProfileSetup',
  MECH_UPLOAD_PROFILE_PHOTO: 'MechanicUploadProfilePhoto',
  MECH_UPLOAD_CERTIFICATE: 'MechanicUploadCertificate',
  MECH_SERVICE_PRICING: 'MechanicServicePricing',
  MECH_KYC_UPLOAD: 'MechanicKycUpload',
  MECH_BANK_DETAILS: 'MechanicBankDetails',
  MECH_EDIT_PROFILE: 'MechanicEditProfile',
  MECH_JOB_DETAILS: 'MechanicJobDetails',
  MECH_CHAT: 'MechanicChat', // Added new route
  MECH_LIVE_TRACKING: 'MechanicLiveTracking',
  USER_PROFILE: 'UserProfile',
  ADMIN_DASHBOARD: 'AdminDashboard',
};
